SET NAMES utf8mb4;

START TRANSACTION;

ALTER TABLE menu_categories ADD COLUMN IF NOT EXISTS description TEXT NULL;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS image_url VARCHAR(500) NULL;

DELETE mi
FROM menu_items mi
JOIN menu_categories mc ON mc.id = mi.category_id
WHERE mc.type = 'catering'
  AND mc.name IN ('FOOD TRAYS', 'FROZEN READY TO EAT MEALS');

DELETE FROM menu_categories
WHERE type = 'catering'
  AND name IN ('FOOD TRAYS', 'FROZEN READY TO EAT MEALS');

INSERT INTO menu_categories (name, type, description) VALUES
('FOOD TRAYS', 'catering', CONCAT(
  'MEDIUM BILAO PLATTER - 5-8 PAX PER ORDER', '\n',
  'LARGE BILAO PLATTER - 10-15 PAX PER ORDER', '\n',
  'FOOD TRAYS - 8-10 PAX PER ORDER', '\n',
  'PANCIT BILAO - 10-15 PAX PER ORDER'
)),
('FROZEN READY TO EAT MEALS', 'catering', NULL);

SET @cat_food_trays = (SELECT id FROM menu_categories WHERE name = 'FOOD TRAYS' AND type = 'catering' ORDER BY id DESC LIMIT 1);
SET @cat_frozen = (SELECT id FROM menu_categories WHERE name = 'FROZEN READY TO EAT MEALS' AND type = 'catering' ORDER BY id DESC LIMIT 1);

INSERT INTO menu_items (category_id, name, description, price, image_url, is_available) VALUES
(@cat_food_trays, 'BILAO PLATTER', 'Baked mussels, pork adobo, fried chicken, buttered shrimps, steamed veggies, grilled liempo, daing na bangus, salted egg, ensaladang talong, mangga''t alamang', 1700.00, NULL, 1),
(@cat_food_trays, 'PANCIT', 'Classic Filipino noodles tossed with fresh vegetables and a light savory sauce then topped with crispy bagnet for added texture.', 1100.00, NULL, 1),
(@cat_food_trays, 'PANCIT MALABON', 'A Filipino favorite featuring thick rice noodles tossed in a rich, savory shrimp-based sauce. Topped with a generous medley of seafood such as shrimp and squid, sliced hard-boiled eggs, and crunchy chicharon bits.', 1200.00, NULL, 1),
(@cat_food_trays, 'BAKED SALMON', 'A premium, heart healthy dish featuring a tender salmon fillet baked to perfection. Topped with cream, corn and carrots and cheese.', 1900.00, NULL, 1),
(@cat_food_trays, 'SINIGANG NA SALMON SA MISO', 'A comforting Filipino sour soup made with salmon belly. The savory depth of miso paste balances the signature tamarind tartness, complemented by fresh radish and mustard greens', 1300.00, NULL, 1),
(@cat_food_trays, 'LAPU LAPU DELA REYNA', 'A traditional celebratory dish featuring fresh Grouper (Lapu Lapu) steamed to preserve its delicate flavor. It is uniquely dressed with a creamy mayo based topping and garnished with finely chopped carrots, eggs, pickles, bell peppers and fried garlic.', 1700.00, NULL, 1),
(@cat_food_trays, 'SWEET AND SOUR LAPU LAPU', 'Crispy deep fried Lapu Lapu smothered in vibrant, tangy sweet and sour sauce. This classic dish is balanced with bell peppers, onions and pineapple chunks for a perfect blend of flavors.', 1700.00, NULL, 1),
(@cat_food_trays, 'CHINESE STYLE STEAMED LAPU LAPU', 'A fresh whole Lapu Lapu gently steamed to perfection. Topped with savory blend of soy sauce, ginger and scallions for a delicate and traditional flavor.', 1600.00, NULL, 1),
(@cat_food_trays, 'SINIGANG NA HIPON', 'A Filipino classic. Fresh shrimps simmered in a vibrant, sour tamarind broth with medley of local vegetables like radish, eggplant and long beans.', 1200.00, NULL, 1),
(@cat_food_trays, 'EBI TEMPURA', 'Light and crispy Japanese-style battered shrimp. Deep fried until golden and served with a traditional sweet and savory tempura dipping sauce.', 1400.00, NULL, 1),
(@cat_food_trays, 'SHRIMP WITH ALIGUE', 'Succulent shrimp sauteed in a rich flavorful sauce made from Aligue (crab fat). This dish is indulgent, savory and perfect for seafood lovers.', 1400.00, NULL, 1),
(@cat_food_trays, 'GAMBAS', 'A popular Spanish inspired appetizer featuring plump shrimp sauteed in olive oil, garlic and a hint of chili for a spicy kick.', 1450.00, NULL, 1),
(@cat_food_trays, 'FILIPINO STYLE SHRIMP GAMBAS', 'Juicy shrimp cooked in a rich Filipino style banana ketchup based sauce with garlic, onion leek, bell pepper and chili, offering a bold balance of sweetness, savoriness and heat.', 1400.00, NULL, 1),
(@cat_food_trays, 'SWEET CHILLI SHRIMP', 'Succulent shrimp sauteed with chili and finished with honey creating a perfect balance of natural sweetness and gentle heat.', 1300.00, NULL, 1),
(@cat_food_trays, 'SHRIMP IN NANTUA SAUCE', 'Tender shrimp served in a smooth, creamy Nantua style sauce made with butter, aromatics and cream, finished with a rich yet delicate seafood forward flavor.', 1400.00, NULL, 1),
(@cat_food_trays, 'CAMARON REBOSADO', 'Golden, crispy battered shrimp fried to perfection and served with a classic sweet and sour dipping sauce.', 1400.00, NULL, 1),
(@cat_food_trays, 'TYPHOON SHELTER CRABS', 'Crispy fried crabs tossed in a bold Typhoon Shelter style mix of crunchy garlic, fermented black beans, chili and aromatic spices.', 1800.00, NULL, 1),
(@cat_food_trays, 'SWEET CHILI CRABS', 'Crispy fried crabs tossed in a Filipino style sweet chili sauce with a hint of garlic and chili heat. Sweet, savory and mildly spicy with comforting local taste.', 1800.00, NULL, 1),
(@cat_food_trays, 'GRILLED SQUID', 'Whole squid stuffed with a savory seasoned filling, grilled until tender and lightly charred.', 1400.00, NULL, 1),
(@cat_food_trays, 'BAKED MUSSELS', 'Fresh mussels topped with a savory cheese mixture and baked until golden and bubbly. Rich, cheesy and flavorful with a natural seafood sweetness.', 1000.00, NULL, 1),
(@cat_food_trays, 'TANIGUE IN LEMON BUTTER SAUCE', 'Fresh tanigue cooked until tender and lightly golden, finished with a bright lemon butter sauce.', 1800.00, NULL, 1),
(@cat_food_trays, 'SEAFOOD KARE KARE', 'A Filipino favorite featuring fresh seafood cooked separately and served with a rich, savory peanut sauce and vegetables. Creamy, nutty and well balanced, allowing the natural flavors of the seafood to stand out.', 1500.00, NULL, 1),
(@cat_food_trays, 'SEAFOOD BOIL', 'A generous mix of fresh seafood, sausage and sweet corn tossed in a flavorful savory butter sauce.', 3000.00, NULL, 1),
(@cat_food_trays, 'HONEY AND LEMON SOY GLAZED TUNA', 'Tender tuna glazed with a blend of honey, soy sauce and fresh lemon, creating a perfect balance of sweet, savory and citrus notes. Lightly cooked to highlight the natural richness of the tuna and finished with a glossy, flavorful glaze.', 1700.00, NULL, 1),
(@cat_food_trays, 'GRILLED TUNA BELLY', 'Rich and juicy tuna belly grilled until lightly charred and tender, bringing out its natural oils and deep seafood flavor. Savory, smoky and satisfying.', 1200.00, NULL, 1),
(@cat_food_trays, 'GRILLED TUNA PANGA', 'Juicy tuna panga grilled until lightly charred with a nice smoky flavor.', 1200.00, NULL, 1),
(@cat_food_trays, 'SWEET AND SOUR FISH FILLET', 'Crispy cream dory fillet tossed in a bright sweet and sour sauce with perfect balance of tangy and sweet flavors.', 1100.00, NULL, 1),
(@cat_food_trays, 'CALAMARES', 'Crispy fried squid rings coated in a light, crunchy batter served with a rich garlic dipping sauce. Golden, tender and flavorful.', 1100.00, NULL, 1),
(@cat_food_trays, 'PAKSIW NA HASA HASA', 'Fresh hasa hasa simmered in a tangy vinegar broth with garlic, ginger and peppercorns. Light, savory and comforting with a classic sour kick.', 1200.00, NULL, 1),
(@cat_food_trays, 'CHINESE STYLE STEAMED PAMPANO', 'Fresh pampano gently steamed and finished with a light soy-based sauce, garlic, ginger and aromatics.', 1200.00, NULL, 1),
(@cat_food_trays, 'ADOBONG PUSIT SA GATA', 'Tender squid simmered in a savory adobo sauce enriched with creamy coconut milk, delivering a rich balance of salty, tangy and gently sweet flavors. Creamy and comforting.', 1400.00, NULL, 1),
(@cat_food_trays, 'BEEF MORCON', 'Tender beef roll stuffed with savory fillings, slow cooked in a rich tomato based sauce until flavorful and fork tender.', 1600.00, NULL, 1),
(@cat_food_trays, 'BURGER STEAK WITH GRAVY', 'Juicy beef patties pan seared and smothered in a rich, savory gravy.', 1300.00, NULL, 1),
(@cat_food_trays, 'BEEF KARE KARE', 'Tender beef slow cooked and served with a rich, savory peanut sauce and vegetables.', 1400.00, NULL, 1),
(@cat_food_trays, 'BEEF STEAK', 'Tender slices of beef cooked in a soy based sauce with onions and a hint of citrus. Rich, flavorful and comforting.', 1200.00, NULL, 1),
(@cat_food_trays, 'BEEF CALDERETA', 'Tender beef simmered in a rich tomato based sauce with vegetables, delivering a bold, hearty flavor with a hint of spice.', 1300.00, NULL, 1),
(@cat_food_trays, 'AUSTRALIAN RIB EYE SALPICAO', 'Tender imported Australian rib eye cubes seared with garlic and rosemary, finished with a light soy based seasoning. Juicy, aromatic and full of flavor.', 2700.00, NULL, 1),
(@cat_food_trays, 'BEEF MECHADO', 'Classic Filipino comfort food made with tender beef slowly braised in a tomato based sauce with carrots, potatoes and bell peppers.', 1300.00, NULL, 1),
(@cat_food_trays, 'BEEF GYUDON', 'Tender, thin sliced beef and sweet onions gently simmered in a light soy based sauce a subtle touch of sweetness.', 1300.00, NULL, 1),
(@cat_food_trays, 'KOREAN BEEF STEW', 'Slow braised beef cooked until fork tender in a deep soy based sauce with a gentle sweetness and rich umami. Finished with toasted sesame seeds and sprinkle of chili flakes, adding a mild heat that lifts the dish while keeping it warm, comforting and well balanced.', 1300.00, NULL, 1),
(@cat_food_trays, 'MEATBALLS WITH GRAVY', 'Juicy, well seasoned meatballs cooked until tender and coated in a smooth savory gravy.', 1300.00, NULL, 1),
(@cat_food_trays, 'BEEF STROGANOFF', 'Tender strips of beef simmered in a creamy mushroom sauce enriched with a touch of sour cream for a smooth, slightly tangy finish.', 1300.00, NULL, 1),
(@cat_food_trays, 'BEEF WITH BROCCOLI', 'Tender slices of beef stir fried with crisp broccoli in a savory soy based sauce. Simple, hearty and well balanced with a clean flavors that make it a dependable classic', 1300.00, NULL, 1),
(@cat_food_trays, 'CREAMY BEEF', 'Tender slices of beef cooked in a smooth creamy sauce with a rich comforting flavor.', 1300.00, NULL, 1),
(@cat_food_trays, 'BEEF MISONO', 'Thinly sliced beef stir fried in a savory soy based sauce with a gentle sweetness and deep umami. Served with a buttery mix of beansprouts, carrots and cabbage adding freshness and richness that balanced the bold, comforting flavors of the beef', 1300.00, NULL, 1),
(@cat_food_trays, 'BEEF IN SINIGANG GRAVY', 'Tender beef cooked in a tangy sinigang style gravy with that signature sour kick. Bold yet comforting, with a rich savory depth balanced by bright acidity - familiar Filipino flavors presented in a hearty satisfying dish.', 1300.00, NULL, 1),
(@cat_food_trays, 'BEEF TEPPANYAKI', 'Thinly sliced beef tenderloin quickly seared over high heat and tossed in a savory Japanese style sauce.', 2700.00, NULL, 1),
(@cat_food_trays, 'BEEF BULALO', 'Slow simmered beef shank cooked until tender, releasing rich marrow into a clear flavorful broth.', 1600.00, NULL, 1),
(@cat_food_trays, 'BEEF NACHOS WITH SALSA AND CHEESE', 'Crispy tortilla chips layered with seasoned beef, melted cheese and fresh salsa. Savory, cheesy and vibrant.', 1200.00, NULL, 1),
(@cat_food_trays, 'LENGUA IN MUSHROOM SAUCE', 'Tender, slow cooked beef tongue sliced and coated in a rich creamy mushroom sauce. Smooth, savory and deeply comforting, with a melt in the mouth texture balanced by earthy mushroom flavors.', 2100.00, NULL, 1),
(@cat_food_trays, 'BEEF IN MUSHROOM SAUCE', 'Juicy beef cooked in a smooth mushroom sauce mixed with tender carrots and sweet corn.', 1500.00, NULL, 1),
(@cat_food_trays, 'BEEF KOFTA WITH GARLIC YOGHURT SAUCE', 'Seasoned beef kofta balls pan seared until juicy and flavorful, served with a cool, creamy garlic yoghurt sauce.', 1300.00, NULL, 1),
(@cat_food_trays, 'PORK ASADO', 'Slow braised pork cooked until tender in a sweet savory sauce with soy sauce, sugar and spices creating a rich comforting dish.', 1200.00, NULL, 1),
(@cat_food_trays, 'PORK DINAKDAKAN', 'Grilled and chopped pork tossed with onion and chilies, dressed in vinegar and mayonnaise for a tangy, creamy balance, delivering a smoky bold dish with a rich yet refreshing finish', 1200.00, NULL, 1),
(@cat_food_trays, 'WHITE MENUDO', 'Your usual pork menudo ingredients - tender pork, pork liver, potatoes, carrots, bell peppers, green peas, raisins. simmered in a rich, creamy sauce instead of tomato base, finished with sliced Vienna sausage instead of hotdog.', 1500.00, NULL, 1),
(@cat_food_trays, 'PORK HUMBA', 'Slow braised pork cooked until tender in a rich sweet savory sauce of soy sauce, garlic, bay leaves and dried oregano, enriched with fermented black beans and banana blossoms. Finished with sliced hard boiled eggs on top.', 1200.00, NULL, 1),
(@cat_food_trays, 'HUNGARIAN SAUSAGE WITH CARAMELIZED ONION', 'Juicy Hungarian style sausage cooked until lightly crisp, served with slow caramelized onions and finished with our own blend of seasonings for a bold, savory dish with a touch of natural sweetness.', 950.00, NULL, 1),
(@cat_food_trays, 'PORK HAMONADO', 'Tender pork strips simmered in sweet pineapple juice with slices of hotdog, creating a glossy, sweet savory sauce.', 1200.00, NULL, 1),
(@cat_food_trays, 'PORK HAMONADO ROLL', 'Tender pork rolled and filled with cheese, pork fat and hotdog then cooked in a sweet pineapple based hamonado sauce.', 1500.00, NULL, 1),
(@cat_food_trays, 'PORK SISIG', 'Chopped pork cooked until crispy and tender, then tossed in mayonnaise and our own blend of sauce. Finished with onions and chilies.', 1200.00, NULL, 1),
(@cat_food_trays, 'PORK MENUDO', 'Tender pork simmered in rich tomato based sauce with potatoes, carrots, bell pepper, pork liver, raisins, green peas and hotdog.', 1300.00, NULL, 1),
(@cat_food_trays, 'PORK IN BLACK PEPPER SAUCE', 'Tender pork slices sauteed with garlic and onions, coated in a rich black pepper sauce made with crushed peppercorns, soy sauce and a touch of butter, finished with bell peppers and onion leeks for added aroma and a warm peppery kick.', 1400.00, NULL, 1),
(@cat_food_trays, 'INIHAW NA LIEMPO', 'Pork belly simply seasoned with salt and pepper, grilled until smoky and juicy, served with a classic soy sauce and vinegar dip on the side.', 1200.00, NULL, 1),
(@cat_food_trays, 'BBQ LIEMPO', 'Juicy pork belly slices marinated in a sweet savory blend of soy sauce, calamansi, garlic, brown sugar and spices then grilled slowly until smoky, caramelized and tender.', 1200.00, NULL, 1),
(@cat_food_trays, 'BBQ PORK RIBS', 'Slow oven baked until tender and juicy, then brushed generously with our own blend of bbq sauce.', 1500.00, NULL, 1),
(@cat_food_trays, 'PORK ADOBO', 'Classic Filipino pork adobo slow simmered until tender in soy sauce, garlic, bay leaves and black peppercorns.', 1200.00, NULL, 1),
(@cat_food_trays, 'THAI GRILLED PORKCHOP', 'Juicy pork chop marinated in a Thai style blend of fish sauce, garlic, palm sugar and spices then grilled until lightly charred and aromatic. Finished with a hint of smokiness and served with a tangy, slightly spicy dipping sauce that brings out the bold Thai flavors.', 1300.00, NULL, 1),
(@cat_food_trays, 'BOPIS', 'A bold Filipino classic made from finely chopped pork innards sauteed with onions, garlic, bell peppers, carrots, radish, chilies and spices. Cooked until rich and aromatic with a balance of heat and savory depth.', 1200.00, NULL, 1),
(@cat_food_trays, 'BAGNET KARE KARE', 'Crispy bagnet served in a rich, savory kare kare sauce, paired with classic vegetables such as eggplant, pechay and sitaw. Served with alamang on the side.', 1300.00, NULL, 1),
(@cat_food_trays, 'SINIGANG NA BABOY', 'Classic Filipino sour soup made with tender pork simmered in a flavorful tamarind based broth complemented by fresh kankong, radish, eggplant and tomatoes.', 1200.00, NULL, 1),
(@cat_food_trays, 'LUMPIANG SHANGHAI', 'Crispy golden spring rolls filled with savory blend of ground pork, carrots, onions and seasonings, then deep fried until crunchy, Served with sweet chili dip.', 1100.00, NULL, 1),
(@cat_food_trays, 'PORK STEAK', 'Juicy pork chops pan seared and simmered in a savory soy and calamansi sauce, topped with sauteed onions.', 1100.00, NULL, 1),
(@cat_food_trays, 'TOKWA''T BABOY', 'Crispy fried tofu served with our own house made bagnet, accompanied by a classic soy sauce - vinegar dipping sauce with onions and chili.', 1000.00, NULL, 1),
(@cat_food_trays, 'PORK EMBUTIDO', 'Traditional Filipino style meatloaf made from seasoned ground pork mixed with raisins and pickle relish, rolled with egg and vienna sausage then steamed until tender and sliced to serve.', 1400.00, NULL, 1),
(@cat_food_trays, 'PORK TONKATSU', 'Crispy, golden breaded pork cutlet, deep fried until perfectly crunchy outside and juicy inside. Served sliced for easy eating with fresh shredded cabbage and a rich, savory tonkatsu sauce.', 1200.00, NULL, 1),
(@cat_food_trays, 'CRISPY PORK RIBS WITH VINEGAR DIP', 'Deep fried pork ribs cooked until golden and crackling crisp on the outside while remaining tender and juicy inside. Served with a sharp, garlicky vinegar dip.', 1300.00, NULL, 1),
(@cat_food_trays, 'PORK BBQ SKEWER', 'Tender pork pieces marinated in a classic Filipino bbq sauce then grilled until smoky, juicy and lightly caramelized. Finished with a glossy glaze that delivers the signature sweet savory flavor Filipinos love.', 1200.00, NULL, 1),
(@cat_food_trays, 'SWEET AND SOUR PORK', 'Crispy bite sized pork tossed in a glossy sweet and sour sauce made with pineapple, bell peppers and onions.', 1300.00, NULL, 1),
(@cat_food_trays, 'BAKED CHICKEN ALA KING', 'Tender chicken pieces baked in a rich, creamy sauce with mushrooms, bell peppers and other vegetables. Comforting and indulgent, this oven baked classic delivers smooth, savory flavors with a lightly golden finish topped with parmesan cheese.', 1400.00, NULL, 1),
(@cat_food_trays, 'GRILLED CAJUN CHICKEN', 'Juicy chicken marinated in a mild cajun herb and spice blend, then grilled to a lightly charred, smoky finish. Served with rich savory gravy.', 1200.00, NULL, 1),
(@cat_food_trays, 'ITALIAN HERBED CHICKEN', 'Tender chicken oven baked and infused with a fragrant blend of Italian herbs, garlic and olive oil. Slowly cooked to lock in moisture, delivering a juicy aromatic dish with clean, savory flavors and a lightly golden finish. Served with rich au jus gravy.', 1200.00, NULL, 1),
(@cat_food_trays, 'BRAISED CHICKEN FEET IN CHILI BEAN SAUCE', 'Slow braised chicken feet simmered until tender and gelatinous, coated in a rich chili bean sauce with deep umami notes.', 1100.00, NULL, 1),
(@cat_food_trays, 'CHICKEN LOLLIPOP WITH HONEY MUSTARD SAUCE', 'Crispy, golden fried chicken lollipops prepared from juicy drumettes seasoned and cooked to a crunchy exterior while staying tender inside. Served with smooth honey mustard sauce.', 1200.00, NULL, 1),
(@cat_food_trays, 'ROAST CHICKEN IN TAMARIND GRAVY', 'Juicy roast chicken cooked until golden and tender served with a savory tamarind gravy that delivers gentle acidity and deep umami.', 1200.00, NULL, 1),
(@cat_food_trays, 'GRILLED CHICKEN IN CREAM SAUCE', 'Juicy grilled chicken cooked to a lightly charred finish, served with a smooth, savory cream sauce.', 1200.00, NULL, 1),
(@cat_food_trays, 'FRIED CHICKEN WITH GRAVY', 'Golden, crispy fried chicken prepared using our special house recipe, fried until perfectly crunchy on the outside and juicy inside. Served with rich, savory gravy made to complement the crisp coating for a comforting signature favorite.', 1200.00, NULL, 1),
(@cat_food_trays, 'GRILLED CHICKEN TERIYAKI', 'Juicy chicken marinated and grilled to a lightly charred finish, then brushed with a glossy teriyaki glaze. Savory and well balanced, this dish delivers classic Japanese inspired flavors with a subtle sweetness that enhances the smoky grilled notes.', 1200.00, NULL, 1),
(@cat_food_trays, 'CHICKEN CORDON BLEU', 'Tender chicken breast rolled with ham and cheese, breaded and fried until golden and crisp.', 1500.00, NULL, 1),
(@cat_food_trays, 'CHICKEN ADOBO', 'Classic Filipino chicken simmered in soy sauce, vinegar, garlic, bay leaves and peppercorns until tender and deeply flavorful.', 1100.00, NULL, 1),
(@cat_food_trays, 'CHICKEN BIRYANI WITH RICE', 'Fragrant basmati rice layered with tender chicken cooked in aromatic spices and herbs, then slow cooked to allow the flavors to fully develop. Rich, savory and comforting, this classic dish delivers depth and warmth in every bite.', 1800.00, NULL, 1),
(@cat_food_trays, 'CHICKEN SATAY', 'Marinated chicken skewers grilled until tender and lightly charred, delivering a smoky savory flavor. Served with a rich peanut sauce on the side.', 1200.00, NULL, 1),
(@cat_food_trays, 'CHICKEN INASAL', 'Juicy chicken marinated in our special house inasal blend, then grilled until tender with a lightly charred finish. Infused with classic Filipino flavors and basted as it cooks, this signature dish delivers rich aroma and savory depth.', 1200.00, NULL, 1),
(@cat_food_trays, 'CHICKEN PANDAN', 'Tender chicken marinated in aromatic seasonings, wrapped in fragrant pandan leaves and fried until golden. Juicy and flavorful inside with a subtle herbal aroma from the pandan.', 1200.00, NULL, 1),
(@cat_food_trays, 'CHICKEN BBQ', 'Juicy chicken marinated in our flavorful barbecue blend, then grilled until tender and lightly charred.', 1200.00, NULL, 1),
(@cat_food_trays, 'HAINANESE CHICKEN', 'Poached chicken cooked gently until tender and silky, preserving its natural juiciness and clean flavor. Served in a classic Hainanese style highlighting the simplicity of well cooked chicken with light, savory profile that''s comforting and refined.', 1500.00, NULL, 1),
(@cat_food_trays, 'CHICKEN KEBAB', 'Tender chicken pieces marinated in a blend of spices and herbs, skewered and grilled until juicy with lightly charred finish.', 1200.00, NULL, 1),
(@cat_food_trays, 'CHICKEN TIKKA MASALA', 'Marinated chicken pieces cooked until tender, then simmered in a rich tomato masala sauce infused with aromatic spices and cream.', 1200.00, NULL, 1),
(@cat_food_trays, 'BAKED MAC', '', 1400.00, NULL, 1),
(@cat_food_trays, 'LASAGNA', '', 1400.00, NULL, 1),
(@cat_food_trays, 'CARBONARA', '', 1400.00, NULL, 1),
(@cat_food_trays, 'CHICKEN ALFREDO', '', 1400.00, NULL, 1),
(@cat_food_trays, 'TUNA PESTO', '', 1400.00, NULL, 1),
(@cat_food_trays, 'SPAGHETTI', '', 1400.00, NULL, 1),
(@cat_food_trays, 'PENNE ARRABIATA', '', 1400.00, NULL, 1),
(@cat_food_trays, 'JAPCHAE', '', 1400.00, NULL, 1),
(@cat_food_trays, 'CREAMY VEGETABLE WITH SHRIMP AND QUAIL EGGS', '', 1300.00, NULL, 1),
(@cat_food_trays, 'KANI SALAD', '', 1200.00, NULL, 1),
(@cat_food_trays, 'LUMPIANG UBOD', '', 1200.00, NULL, 1),
(@cat_food_trays, 'LUMPIANG HUBAD', '', 1100.00, NULL, 1),
(@cat_food_trays, 'LAING WITH PORK', '', 1100.00, NULL, 1),
(@cat_food_trays, 'PINAKBET', '', 1100.00, NULL, 1),
(@cat_food_trays, 'CHOPSUEY', '', 1100.00, NULL, 1),
(@cat_food_trays, 'KILAWIN SA PUSO NG SAGING WITH PORK', '', 1100.00, NULL, 1),
(@cat_food_trays, 'BUTTERED VEGGIES', '', 1100.00, NULL, 1),
(@cat_food_trays, 'GARDEN SALAD', '', 1100.00, NULL, 1),
(@cat_food_trays, 'FRUIT PLATTER', '', 1200.00, NULL, 1),
(@cat_food_trays, 'CLUBHOUSE', '', 1100.00, NULL, 1),
(@cat_food_trays, 'ARROZ CALDO', '', 1000.00, NULL, 1),
(@cat_food_trays, 'CHICKEN SOTANGHON SOUP', '', 1200.00, NULL, 1),
(@cat_food_trays, 'PAELLA', '', 2000.00, NULL, 1),
(@cat_food_trays, 'YANG CHOW FRIED RICE', '', 1200.00, NULL, 1),
(@cat_food_trays, 'BUKO PANDAN', '', 1200.00, NULL, 1),

(@cat_frozen, 'BICOL EXPRESS', '', 200.00, NULL, 1),
(@cat_frozen, 'PORK MENUDO', '', 200.00, NULL, 1),
(@cat_frozen, 'PORK SISIG', '', 200.00, NULL, 1),
(@cat_frozen, 'PORK HAMONADO', '', 200.00, NULL, 1),
(@cat_frozen, 'PORK DINUGUAN', '', 200.00, NULL, 1),
(@cat_frozen, 'PORK ADOBO', '', 200.00, NULL, 1),
(@cat_frozen, 'BOPIS', '', 200.00, NULL, 1),
(@cat_frozen, 'BAGNET KARE KARE', '', 200.00, NULL, 1),
(@cat_frozen, 'PORK BINAGOONGAN', '', 200.00, NULL, 1),
(@cat_frozen, 'BEEF CALDERETA', '', 220.00, NULL, 1),
(@cat_frozen, 'BEEF IN SINIGANG GRAVY', '', 220.00, NULL, 1),
(@cat_frozen, 'BURGER STEAK', '', 220.00, NULL, 1),
(@cat_frozen, 'MEATBALLS WITH GRAVY', '', 220.00, NULL, 1),
(@cat_frozen, 'BEEF STEAK', '', 220.00, NULL, 1),
(@cat_frozen, 'BEEF KARE KARE', '', 220.00, NULL, 1),
(@cat_frozen, 'CHICKEN ADOBO', '', 200.00, NULL, 1),
(@cat_frozen, 'MANOK SA PICKLES', '', 200.00, NULL, 1),
(@cat_frozen, 'CHICKEN CALDERETA', '', 200.00, NULL, 1),
(@cat_frozen, 'CHICKEN CURRY', '', 200.00, NULL, 1),
(@cat_frozen, 'PAN FRIED CHICKEN WITH GRAVY', '', 200.00, NULL, 1),
(@cat_frozen, 'LASAGNA', '', 200.00, NULL, 1),
(@cat_frozen, 'BAKED MAC', '', 200.00, NULL, 1),
(@cat_frozen, 'LAING WITH PORK', '', 170.00, NULL, 1),
(@cat_frozen, 'PAKBET WITH SHRIMP', '', 180.00, NULL, 1),
(@cat_frozen, 'ADOBONG SITAW WITH PORK GINILING', '', 180.00, NULL, 1),
(@cat_frozen, 'GINATAANG KALABASA NA MAY SITAW', '', 180.00, NULL, 1),
(@cat_frozen, 'KILAWIN SA PUSO NG SAGING WITH PORK', '', 180.00, NULL, 1),
(@cat_frozen, 'PORK SIOMAI', '', 140.00, NULL, 1),
(@cat_frozen, 'PORK N SHRIMP SIOMAI', '', 180.00, NULL, 1),
(@cat_frozen, 'BARUTAK', '', 200.00, NULL, 1),
(@cat_frozen, 'GINATAANG LANGKA', '', 180.00, NULL, 1),
(@cat_frozen, 'GINISANG KAMIAS', '', 180.00, NULL, 1),
(@cat_frozen, 'LAKSA', '', 200.00, NULL, 1);

COMMIT;